### PR TITLE
include updates for the new DB version

### PR DESCRIPTION
**Pull request by matsmahnken**
include changes made on scripts generating the DB for DB version 0.3

### CODE REVIEW

**Comment by florianhartig** [comment]
Hi Mats, as I understand, these are changes for the 0.3.0 release, so why not merge this into the 0.3.0 branch?

**Comment by matsmahnken** [comment]
Hi Florian, correct! These are changes linked to the 0.3.0 release. Isn't this pull request doing that - merging the changes into branch 0.3.0 from my fork's master branch?

Sorry, I am still not 100 % familiar with the usual git collaboration workflow.

**Comment by florianhartig** [comment]
Sorry, yes, I had seen this now as well. I think it's all fine, the error you are getting is because of the error in 0.3.0. The pull request tests the merged version, if 0.3.0 has an error, then we have the same error after the pull request as well.

**Comment by florianhartig** [comment]
I have just pushed an update to 0.3.0 that I hope takes care of the at least one of the problems. I think I will simply merge this now!

**Comment by florianhartig** [comment]
Actually, you know, what confused me here was that you were asking to pull from matsmahnken:master - you have push rights for this repo, so I would suggest that you either

- push directly in the development branch (e.g. 0.3.0)
- create a new branch on this repo, ideally branching off from development not master, and then create a pull request when you merge back in to the origin branch

**Comment by matsmahnken** [comment]
Alright. My workflow for now has been a mix of directly pushing commits to our development branch (0.3.0) and pull requests from my fork. This was due to what I am doing here locally with the Ubuntu VM for creating the DB and also working on the Windows partition.

But this is a good time to clean up my structure here and start only pushing to the development branch. Thanks for the advice!

**Pull request merged**
