### PR TITLE
Adding the cvegag and cvegbg

### PR DESCRIPTION
**Pull request by trotsiuk**
1. Adding the biomass variables
2. Check if the input data is a data.frame
3. The check for first three column names, adjusted.

```
library(dplyr)
library(ProfoundData)

data.tbl <- tibble(
  lat = rep(20, 10),
  lon = rep(30, 10),
  time = rep(1920, 10),
  dbh_total = c(10:19)
) 
  
class(data.tbl)

writeSim2netCDF(
    df = data.tbl, 
    comment1 = 'Tibble input will not work', 
    folder = "simulation/")

# Error: is.numeric(data) || is.character(data) || is.raw(data) || is.logical(data) is not TRUE


# return tibble not a vector
data.tbl[,4]

# vs
data.tbl[[4]]


data.df <- data.frame(data.tbl)

class(data.df)

writeSim2netCDF(
  df = data.df, 
  comment1 = 'Data.frame input will work', 
  folder = "simulation/")

# return a vector
data.df[,4]
```

Would also suggest to change the `time` column into a `Date` class this will allow to make more flexible `timestep`. Currently it is only 'annual', but there are data with daily and monthly resolution.

### CODE REVIEW

**Comment by florianhartig** [comment]
Hi Vova, thanks for that. The motivation for this makes sense to me - @Rasilgon , is there a technical concern with doing this?

**Comment by Rasilgon** [comment]
Hi, sorry that I did not see this earlier. 

I am not much familiar with netCDF, @Friedrich is the one to be asked here about this function.

We can merge branches, no problem from my side.

**Comment by florianhartig** [comment]
Hi guys, I'm just looking at open issues - why was this never merged?

**Comment by mmahnke** [comment]
Hi guys, I think this can be merged. To me the commits make sense and are necessary to update variable names according to ISIMIP naming conventions and prevent incorrect error message displaying.

And I agree that it would be great to also include the possibility to convert daily/monthly data.

**Pull request merged**
