### PR TITLE
update branch for release 2.2

### PR DESCRIPTION
**Pull request by matsmahnken**
update branch for version 2.2 with changes made for release of CRAN version 2.1

### CODE REVIEW

**Comment by matsmahnken** [comment]
is this the correct way of doing it? or do we merge 2.2 into master later on? sorry for my confusion.

**Comment by matsmahnken** [comment]
would like include some new commits for the next release - do we work in branch 2.2 to prepare for the next release to CRAN? I would like to have it all together, also the commits in this pull request for producing the updated vignettes.

**Comment by florianhartig** [comment]
If we merge this in Master, then people will get confused, because this requires the new database version, right?

Hi Mats, I would continue to work in branch 2.2 without merging - we will probably call this release 0.3.0 later, but that doesn't matter. 

Alternatively, you could do changes that are independent of the new db in an extra branch, but from what I understand, the new db will be available soon, right?

**Comment by matsmahnken** [comment]
Alright, then lets not merge this here. Since I need the changes from master now for producing the vignette of the new version I will start a new branch 0.3.0 off the current state of master and merge 2.2 into it. Then I continue working on 0.3.0 which contains all the commits for the new release. Hope this makes more sense. :)

**Comment by florianhartig** [comment]
Hi Mats, I hope this worked allright, but the normal action would be to update the 2.2 branch from master. You should do this anyway every time you work on a branch.

So, are all changes in the 2.2 now in the 3.0?

**Comment by florianhartig** [comment]
Important thing - don't created a new branch if you want to bring stuff from master in the dev branches.

We usually work in this workflow https://nvie.com/posts/a-successful-git-branching-model/ except that we don't have a release branch, the release branch is CRAN.

**Comment by matsmahnken** [comment]
Hi Florian, sorry I got lost somehow in how to do this. For now I have what I need and the changes from 2.2 are in 0.3.0 which was only one commit.

Next time I would update the branch from master - that is what I wanted to do with this pull request here.

Do you think we need to revert something or do we keep it this way? Thank you for the advice!

**Comment by florianhartig** [comment]
no, if everything from 0.2.2 was taken over to branch 0.3 it's probably OK (I didn't check).

In general, if new things are on master, just go in your branch, and update master, so you pull in the master. 

A pull request is actually like a push to master, only that you don't push actively, but you ask the master to pull. So you don't do it for updates, updates you can pull in your self, you only do it if you want to deploy your changes to other branches

**Comment by matsmahnken** [comment]
Alright, I will follow this system then. Thanks!

**Pull request closed without merging**
